package com.patientpoint.patientpoint-service.config;

import java.util.HashMap;
import java.util.Map;

import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.serialization.StringSerializer;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.kafka.core.*;

/**
 * Generated by Spring Scaffolder
 * Uses dynamic keys: spring.kafka.patientpoint-service-topics
 */
@Configuration
public class KafkaProducerConfig {

  @Value("${spring.kafka.bootstrap-servers}")
  private String bootstrapServers;

  @Value("${spring.kafka.client-id-prefix}")
  private String clientIdPrefix;

  @Value("$spring.kafka.patientpoint-service-topics.topic-new")
  private String topic-newTopic;

  private Map<String, Object> baseProducerProps(String clientIdentifier) {
    Map<String, Object> props = new HashMap<>();
    props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
    props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
    props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
    props.put(ProducerConfig.CLIENT_ID_CONFIG, clientIdPrefix + "-" + clientIdentifier);
    return props;
  }

  @Bean
  public ProducerFactory<String, String> topic-newProducerFactory() {
    return new DefaultKafkaProducerFactory<>(baseProducerProps("topic-newProducer"));
  }

  @Bean
  public KafkaTemplate<String, String> topic-newKafkaTemplate() {
    KafkaTemplate<String, String> template = new KafkaTemplate<>(topic-newProducerFactory());
    template.setDefaultTopic(topic-newTopic);
    return template;
  }
}
