version: '3.8'
services:
  app:
    build: .
    image: ecc
    ports: ["8080:8080"]
    depends_on:
      - mongo
      
    environment:
      SPRING_PROFILES_ACTIVE: local
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]
volumes: { mongo_data: {} }
