server:
  port: 8080
spring:
  application:
    name: ecc
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017
      database: ecc
      ssl:
        enabled: false
logging:
  structured:
    level:
      root: debug
      com.patientpoint: debug
