server:
  port: 8080
spring:
  application:
    name: editorial-publisher
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017
      database: editorial-publisher
      ssl:
        enabled: false
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: editorial-publisher-group
      auto-offset-reset: earliest
logging:
  structured:
    level:
      root: debug
      com.patientpoint: debug
