spring:
  application:
    name: poc-service:1.0.0
  profiles:
    active: local
  data:
    mongodb:
      database: poc-service:1.0.0
      replicaSet: ${MONGODB_REPLICA_SET}
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_HOST}
      readPreference: primary
      readConcern: majority
      writeConcern: MAJORITY
      writeWithJournal: true
      retryWrites: true
mongodb:
  additional-params:
    maxSize: 100
    minSize: 10
    maxWaitTimeMS: 5
    maxConnectionLifeTimeMS: 60000
    maxConnectionIdleTimeMS: 30000
    maintenanceInitialDelayMS: 1000
    maintenanceFrequencyMS: 60000
    heartbeatFrequency: 15000
    connectTimeout: 30000
    readTimeout: 30000
logging:
  structured:
    format:
      console: logstash
    json:
      add:
        application: ${spring.application.name}
        environment: ${SPRING_PROFILES_ACTIVE}
        service: ${spring.application.name}
      rename:
        level: logLevel
        thread_name: thread
        logger_name: logger
        level_value: levelValue
  level:
    root: info
    com.ppt: info
