server:
  port: 8080
spring:
  application:
    name: poc-service:1.0.0
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017
      database: poc-service:1.0.0
      ssl:
        enabled: false
logging:
  structured:
    level:
      root: debug
      com.patientpoint: debug
