spring:
  application:
    name: patientpoint-service
  profiles:
    active: local
  data:
    mongodb:
      database: patientpoint-service
      replicaSet: ${MONGODB_REPLICA_SET}
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_HOST}
      readPreference: primary
      readConcern: majority
      writeConcern: MAJORITY
      writeWithJournal: true
      retryWrites: true
mongodb:
  additional-params:
    maxSize: 100
    minSize: 10
    maxWaitTimeMS: 5
    maxConnectionLifeTimeMS: 60000
    maxConnectionIdleTimeMS: 30000
    maintenanceInitialDelayMS: 1000
    maintenanceFrequencyMS: 60000
    heartbeatFrequency: 15000
    connectTimeout: 30000
    readTimeout: 30000
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: patientpoint-service-group
      auto-offset-reset: earliest
logging:
  structured:
    format:
      console: logstash
    json:
      add:
        application: ${spring.application.name}
        environment: ${SPRING_PROFILES_ACTIVE}
        service: ${spring.application.name}
      rename:
        level: logLevel
        thread_name: thread
        logger_name: logger
        level_value: levelValue
  level:
    root: info
    com.ppt: info
