name: Build and Deploy
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build
        run: ./gradlew build --no-daemon
      - name: Test
        run: ./gradlew test --no-daemon
      - name: Build Docker
        run: docker build -t patientpoint-service .
